config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(index new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
  end

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resource :students, only: %i(edit update), controller: :draw_students do
      collection do
        patch 'bulk_assign'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/group.rb
# frozen_string_literal: true

# Model for Housing Groups
#
# @attr size [Integer] The room size that the Group wants.
# @attr status [String] The state of the group (open, full, finalizing,
#   or locked)
# @attr leader [User] The student that represents the Group.
# @attr members [Array<User>] The members of the group, excluding the leader.
# @attr draw [Draw] The Draw that this Group is in.
# @attr memberships_count [Integer] the number of accepted memberships (counter
#   cache)
# @attr transfers [Integer] the number of transfer students in the group
# @attr lottery_assignment [LotteryAssignment] the lottery assignment for the
#   group
# @attr clip [Clip] The clip that the group is in, if any.
# @attr clip_memberships [Array<ClipMembership>] All clip memberships that the
#   group is associated with, pending or confirmed.
# @attr clip_membership [ClipMembership] The confirmed clip membership for the
#   group, if any.
class Group < ApplicationRecord # rubocop:disable ClassLength
  belongs_to :leader, inverse_of: :led_group, class_name: 'User'
  belongs_to :draw
  has_one :clip_membership, -> { where(confirmed: true) }, dependent: :destroy
  has_one :clip, through: :clip_membership
  has_many :clip_memberships, dependent: :destroy
  has_one :suite, dependent: :nullify
  belongs_to :lottery_assignment
  accepts_nested_attributes_for :suite

  # This before_destroy clears room assignments and needs to be added before
  # the dependent: :delete_all in the memberships association or there won't be
  # any members to update
  before_destroy :remove_member_rooms

  has_many :memberships, dependent: :delete_all
  has_many :full_memberships, -> { where(status: 'accepted') },
           class_name: 'Membership', inverse_of: :group
  has_many :members, through: :full_memberships, source: :user

  delegate :number, to: :lottery_assignment, prefix: :lottery, allow_nil: true
  delegate :number, to: :suite, prefix: :suite, allow_nil: true

  enum status: %w(open closed finalizing locked)

  # validates :draw, presence: true
  validates :status, presence: true
  validates :size, presence: true
  validates :leader, presence: true, inclusion: { in: ->(g) { g.members } }
  validates :memberships_count, numericality: { greater_than_or_equal_to: 0 }
  validates :transfers, presence: true,
                        numericality: { greater_than_or_equal_to: 0,
                                        only_integer: true }

  validate :validate_suite_size_inclusion,
           if: ->() { will_save_change_to_size? }
  validate :validate_members_count, if: ->(g) { g.size.present? }
  validate :validate_status, if: ->(g) { g.size.present? }
  validate :validate_lottery_assignment,
           if: -> { will_save_change_to_lottery_assignment_id? }

  before_validation :add_leader_to_members, if: ->(g) { g.leader.present? }
  after_save :update_status!,
             if: ->() { saved_change_to_transfers || saved_change_to_size }
  before_update :freeze_lottery,
                if: -> { will_save_change_to_lottery_assignment_id? }
  after_update :remove_clip_memberships,
               if: ->() { changed_draw_with_clip_memberships? }
  after_destroy :restore_member_draws, if: ->(g) { g.draw.nil? }
  after_destroy :notify_members_of_disband
  after_destroy :destroy_lottery_assignment,
                if: ->(g) { g.lottery_assignment.present? }

  attr_reader :remove_ids

  scope :order_by_lottery,
        -> { joins(:lottery_assignment).order('lottery_assignments.number') }

  # Generate the group name
  #
  # @return [String] the group's name
  def name(*opts)
    base = "#{leader.full_name}'s Group"
    opt_strs = opts.map { |o| name_str(o) }.compact.join(', ')
    return base unless opt_strs.present?
    "#{base} (#{opt_strs})"
  end

  # Updates the status to match the group size (open when fewer members than
  # the size, and full when they are the same). Uses `update_columns` to avoid a
  # SystemStackError under certain circumstances (skips callbacks).
  def update_status!
    assign_new_status
    return unless status && valid?
    update_columns(status: status) # rubocop:disable Rails/SkipsModelValidations
    send_locked_email if locked?
  end

  # Get the group's membership requests
  #
  # @return [Array<Membership>] the group's memberships with a requested status
  def requests
    memberships.select { |m| m.status == 'requested' }
  end

  # Get the group's membership invitations
  #
  # @return [Array<Membership>] the group's memberships with an invited status
  def invitations
    memberships.select { |m| m.status == 'invited' }
  end

  # Get all of the non-accepted memberships for the group
  #
  # @return [Array<Membership>] the memberships that are not accepted
  def pending_memberships
    memberships.where.not(status: 'accepted')
  end

  # Get the group's members that can be removed
  #
  # @return [Array<User>] the members of the group with the exception of the
  #   group leader
  def removable_members
    members.reject { |u| u.id == leader_id }
  end

  # Remove specified members
  #
  # @param ids [Array<User>] members of the group
  # @return [Array<User>] the remaining members of the group after deletion
  def remove_members!(ids:)
    ids.delete_if { |u| u == leader_id }
    memberships.where(user_id: ids).delete_all
    # rubocop:disable Rails/SkipsModelValidations
    decrement!(:memberships_count, ids.size)
    # rubocop:enable Rails/SkipsModelValidations
    update_status!
  end

  # Get the group's locked/finalized members
  #
  # @return [Array<User>] the users who have locked their membership
  def locked_members
    full_memberships.where(locked: true).map(&:user)
  end

  # Check if all members have locked their memberships
  #
  # @return [Boolean] true if the group can be locked
  def lockable?
    (members - locked_members).empty? && members_count == size
  end

  # Check if there are any locked memberships
  #
  # @return [Boolean] true if there are any unlocked members
  def unlockable?
    !locked_members.empty? && suite.nil?
  end

  # Check if the group is full
  #
  # @return [Boolean] true if the group's size equals the number of members
  #   in it
  def full?
    members_count == size
  end

  # Return the lottery number assigned to the group, if present
  #
  # @return [Integer, nil] the number, or nil if it isn't present
  def lottery_number
    return nil unless lottery_assignment
    lottery_assignment.number
  end

  # Check if there is an open invitation to join the provided clip
  #
  # @param [Clip] the clip to check for its invitation status
  # @return [Boolean] true if invited to join the given clip
  def invited_to_clip?(clip)
    clip_memberships.where(clip_id: clip.id, confirmed: false).present?
  end

  private

  def name_str(opt)
    case opt
    when :with_size
      Suite.size_str(size)
    when :with_year
      leader.class_year.to_s
    end
  end

  def notify_members_of_disband
    members.each do |m|
      StudentMailer.disband_notification(user: m).deliver_later
    end
  end

  def remove_clip_memberships
    clip_memberships.each(&:destroy)
  end

  def send_locked_email
    members.each do |m|
      StudentMailer.group_locked(user: m).deliver_later
    end
  end

  # override default attribute getter to include transfers
  def members_count
    return 0 unless memberships_count || transfers
    return memberships_count unless transfers
    return transfers unless memberships_count
    memberships_count + transfers
  end

  def add_leader_to_members
    members << leader unless members.include? leader
  end

  def validate_suite_size_inclusion
    # TODO: if we start seeing this pattern (draw.present? branching logic) more
    # often then we can extract special group functionality into a subclass that
    # still talks to the same table in the db to keep things clean.
    if draw.present?
      return if draw.open_suite_sizes.include? size
      errors.add :size, 'must be a suite size included in the draw'
    else
      return if SuiteSizesQuery.call.include? size
      errors.add :size, 'must be a valid suite size'
    end
  end

  def validate_members_count
    return unless members_count > size
    errors.add :members, "can't be greater than the size (#{size})"
  end

  def validate_status
    return unless will_save_change_to_status?
    case status
    when 'open'
      validate_open
    when 'locked'
      validate_locked
    else
      validate_not_open
    end
  end

  def validate_open
    return unless members_count >= size
    errors.add :status, 'can only be open when fewer members than size'
  end

  def validate_not_open
    return if full?
    errors.add :status, "can only be #{status} when members equal size"
  end

  def restore_member_draws
    members.each { |u| u.restore_draw.save }
  end

  def remove_member_rooms
    ActiveRecord::Base.transaction { members.update(room_id: nil) }
  rescue
    throw(:abort)
  end

  def validate_locked
    validate_not_open
    return if lockable?
    errors.add :status, 'can only be locked when all members have locked'
  end

  def validate_lottery_assignment
    return unless lottery_assignment.present?
    if clip.present?
      validate_lottery_for_clipped
    else
      validate_lottery_for_unclipped
    end
  end

  def validate_lottery_for_clipped
    return if clip == lottery_assignment.clip
    errors.add(:lottery_assignment, 'must belong to the same clip')
  end

  def validate_lottery_for_unclipped
    return if clip.present?
    return if lottery_assignment.groups.length == 1 &&
              lottery_assignment.group == self
    errors.add(:lottery_assignment, 'can only have one group unless clipped')
  end

  def freeze_lottery
    if lottery_assignment_id_in_database.present? &&
       lottery_assignment_id.present?
      throw(:abort)
    end
  end

  def changed_draw_with_clip_memberships?
    saved_change_to_draw_id && clip_memberships.present?
  end

  def assign_new_status

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

module Admin
  class GroupsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Group.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Group.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# Helper methods for the Groups views
module GroupsHelper
  # Generate the user listing for a group member; includes membership lock
  # status
  #
  # @param member [User] the user
  # @param group [Group] the user's group
  # @return [String] the user listing
  def member_str(member, group)
    membership = member.membership
    locked_str = membership.locked? ? ' (locked)' : ''
    leader_str = member.leader_of?(group) ? ' (leader)' : ''
    link_to(member.full_name, user_path(member)) + leader_str + locked_str
  end

  # Sort an array of groups by lottery number (nil first), then by group leader
  # last name
  #
  # @param groups [Array<Group>] the groups to sort
  # @return [Array<Group>] the sorted groups
  def sort_by_lottery(groups)
    groups.sort_by do |g|
      if g.lottery_number.nil?
        [-Float::INFINITY, g.leader.last_name]
      else
        [g.lottery_number, g.leader.last_name]
      end
    end
  end

  # Displays the status of a group as the capitalization of its current
  # status. In the case of 'closed' it returns Full to maintain the
  # readability.
  #
  # @param [String] the group that's status will be displayed
  # @return [String] the capitalization of the current status
  def display_group_status(group)
    if group.closed?
      'Full'
    elsif group.finalizing?
      'Locking'
    else
      group.status.capitalize
    end
  end

  # Generate the group name with relevant clipping information appended
  #
  # @param [Group] the group needing the appended information
  # @return [String] the group's name
  def clipping_name(group)
    group.name + if group.clip.present?
                   ' (confirmed)'
                 elsif group.clip_memberships.present? && group.clip.blank?
                   ' (invited to clip)'
                 else
                   ''
                 end
  end
end

app/views/groups/_actions.html.erb
<%= link_to 'View', draw_group_path(group.draw, group), class: 'button' %>
<% if policy(group).edit? %>
  <%= link_to 'Edit', edit_draw_group_path(group.draw, group), class: 'button' %>
<% end %>
<% if policy(group).destroy? %>
  <%= link_to 'Disband', draw_group_path(group.draw, group, redirect_path: path), method: :delete,
              data: { confirm:  'Are you sure you want to disband this group?' }, class: 'button alert' %>
<% end %>

app/views/groups/_form.html.erb
<%= simple_form_for [@draw, @group] do |f| %>
  <%= render partial: 'form_fields', locals: { f: f } %>
<% end %>

app/views/groups/_form_fields.html.erb
<div class="form-inputs">
  <%= f.input :size, collection: @suite_sizes %>
  <% if policy(@group).change_leader? %>
    <%= f.association :leader, label_method: :full_name, collection: @leader_students %>
  <% end %>
  <% if policy(@group).advanced_edit? %>
    <%= f.input :remove_ids, label: 'Users to remove', collection: @group.removable_members, label_method: :full_name, as: :check_boxes unless @group.removable_members.empty? %>
    <%= f.input :member_ids, label: 'Users to add', label_method: :full_name, as: :check_boxes, collection: @students %>
    <% if @group.persisted? %>
      <%= f.input :transfers, label: '# transfer students' %>
    <% end %>
  <% end %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>

app/views/groups/_group_details.html.erb
<h1 class="group-name"><%= group.name %></h1>
<dl>
  <dt>Size</dt>
  <dd class="group-size"><%= group.size %></dd>
  <dt>Status</dt>
  <dd class="group-status"><%= display_group_status(group)%></dd>
  <dt>Members</dt>
  <dd>
    <ul>
      <% group.members.includes(:membership).each do |m| %>
        <li class="group-member"><%= member_str(m, group) %></li>
      <% end %>
    </ul>
    <% unless group.transfers.zero? %>
      <dl>
        <dt>Transfers</dt>
        <dd class="transfers"><%= group.transfers %></dd>
      </dl>
    <% end %>
  </dd>
</dl>

app/views/groups/_secondary_report.html.erb
<% if groups.empty? %>
  <p>There are no groups.</p>
<% else %>
  <ul class="tabs" data-tabs id="group-size-tabs">
    <% groups.keys.sort.each do |size| %>
      <li class="tabs-title<%= groups.keys.sort.first == size ? ' is-active' : '' %>">
        <a href="#size-<%= size %>"><%= headerize_size(size) %></a>
      </li>
    <% end %>
  </ul>
  <div class="tabs-content" data-tabs-content="group-size-tabs">
    <% groups.keys.sort.each do |size| %>
      <div class="tabs-panel<%= groups.keys.sort.first == size ? ' is-active' : '' %>" id="size-<%= size %>">
        <% if groups[size].empty? %>
          <p>No groups of size <%= size %></p>
        <% else %>
          <table aria-label="Group Report" class="group-report-1">
            <thead>
              <tr>
                <th scope="col">Group Leader</th>
                <th scope="col">Lottery #</th>
                <th scope="col">Suite</th>
                <th scope="col">Rooms?</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% groups[size].each do |group| %>
                <tr id="group-<%= group.id %>">
                  <th scope="row" data-role="group-leader"><%= group.leader.full_name %></th>
                  <td data-role="group-lottery"><%= group.lottery_number %></td>
                  <td data-role="group-suite"><%= link_to group.suite.name, suite_path(group.suite) if group.suite %> </td>
                  <td data-role="group-room"> <%= group.leader.room.present? ? 'Y' : 'N' %></td>
                  <td class="actions" data-role="group-actions"><%= render actions_partial, group: group, path: path %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/groups/_suites_table.html.erb
<% suites.each do |building, suites_array| %>
  <p class="h4"><em><%= building.name %></em></p>
  <table>
    <thead>
      <tr>
        <td>Suite #</td>
        <td>S</td>
        <td>D</td>
        <td>C</td>
      </tr>
    </thead>
    <tbody>
      <% suites_array.each do |suite| %>
        <tr>
          <td><%= link_to suite.number, suite_path(suite) %></td>
          <td><%= suite.singles.count %></td>
          <td><%= suite.doubles.count %></td>
          <td><%= suite.common_rooms.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Edit #{@group.name}") %>
<h1>Edit <%= @group.name %></h1>
<%= render "form", group: @group %>
<%= link_to 'Cancel', draw_group_path(@draw, @group) %>

app/views/groups/index.html.erb
<% provide(:title, "#{@draw.name} - All Groups") %>
<h1><%= @draw.name %> - All Groups</h1>
<% if @groups.empty? %>
  <p>There are no groups in this draw yet.</p>
<% else %>
  <div class="printable-group-report">
    <% @groups.each do |size, group_array| %>
      <h2><%= headerize_size(size) %></h2>
      <table>
        <thead>
          <tr>
            <td>Group Leader</td>
            <td>Other Members</td>
            <% if current_user.admin? %>
              <td>Transfers</td>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% group_array.each do |group| %>
            <tr>
              <td data-role="group-leader">
                <% if policy(group).show? %>
                  <%= link_to group.leader.full_name, draw_group_path(@draw, group) %>
                <% end %>
              </td>
              <td data-role="group-members"><%= group.members.map(&:full_name).join(', ') %></td>
              <% if current_user.admin? %>
                <td data-role="group-transfers"><%= group.transfers %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>
<% if policy(@draw).show? %>
  <%= link_to 'Return to draw', draw_path(@draw) %>
<% end %>

app/views/groups/invite.html.erb
<% provide(:title, "#{@group.name} - Edit Invitations") %>
<h1><%= @group.name %> - Edit Invitations</h1>
<%= simple_form_for [@draw, @group], url: send_invites_draw_group_path(@draw, @group) do |f| %>
  <%= f.input :invitations, label: 'Students to invite', as: :check_boxes, label_method: :full_name, collection: @students %>
  <%= f.button :submit, 'Send Invitations' %>
<% end %>
<%= link_to 'Return to group', draw_group_path(@draw, @group) %>

app/views/groups/new.html.erb
<% provide(:title, 'Add Group') %>
<h1>Add Group</h1>
<%= render "form", group: @group %>
<%= link_to 'Cancel', draw_path(@draw) %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render 'group_details', group: @group %>
<% if policy(@group).view_pending_members? %>
  <% unless @group.requests.empty? %>
    <h2 class="group-requests h4">Requests</h2>
    <ul>
      <% @group.requests.each do |r| %>
        <% if policy(r.user).show? %>
          <li class="group-request">
            <%= link_to r.user.full_name, user_path(r.user) %>
            <% if policy(r).accept_request? %>
              (<%= link_to 'accept',
               accept_request_group_membership_path(@group, r), method: :put %><%= policy(r).reject_pending? ? ' / ' : ')' %>
           <% end %>
           <% if policy(r).reject_pending? %>
             <%= '(' unless policy(r).accept_request? %><%= link_to 'reject', reject_pending_group_membership_path(@group, r), method: :put %>)
           <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
  <% unless @group.invitations.empty? %>
    <h2 class="group-invitations h4">Invitations</h2>
    <ul>
      <% @group.invitations.each do |i| %>
        <% if policy(i.user).show? %>
          <li class="group-invitation">
            <%= link_to i.user.full_name, user_path(i.user) %>
            <% if policy(i).reject_pending? %>
              (<%= link_to 'rescind', reject_pending_group_membership_path(@group, i), method: :put %>)
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>
<hr style="border-color: #DDDDDD;" />
<% if @group.clip.present? %>
  <h2 class="clip-information h4">Your Clip</h2>
  <%= render 'clips/clip_details', clip: @group.clip %>
  <hr style="border-color: #DDDDDD;" />
<% elsif @clip_invites.length.positive? %>
  <h2 class="clip-invites h4">Clip Invitations</h2>
  <ul>
    <% @clip_invites.each do |m| %>
      <li class="clip-invitation" id="clip-membership-<%= m.id %>">
        <%= link_to m.clip.name, clip_path(m.clip) if policy(m.clip).show? %>
        <% if policy(m).accept? %>
          (<%= link_to 'Accept Invitation', clip_membership_path(m), method: :patch %><%= policy(m).reject? ? ' / ' : ')' %>
        <% end %>
        <% if policy(m).reject? %>
          <%= '(' unless policy(m).accept? %><%= link_to 'Reject Invitation', clip_membership_path(m), method: :delete %>)
        <% end %>
      </li>
    <% end %>
  </ul>
  <hr style="border-color: #DDDDDD;" />
<% end %>
<div>
  <% if @membership.present? %>
    <%= link_to 'Accept Invitation', accept_invitation_group_membership_path(@group, @membership), method: :put, class: 'button' if policy(@membership).accept_invitation? %>
    <%= link_to 'Lock Membership', finalize_membership_group_membership_path(@group, @membership), method: :put, class: 'button' if policy(@membership).finalize_membership? %>
    <% if policy(@membership).leave? %>
      <%= link_to 'Leave group', leave_group_membership_path(@group, @membership), method: :delete, class: 'button alert' %>
    <% end %>
  <% end %>
  <%= link_to 'Edit', edit_draw_group_path(@draw, @group), class: 'button secondary' if policy(@group).edit? %>
  <%= link_to 'Request To Join', request_group_membership_path(@group), method: :post, class: 'button secondary' if policy(Membership.new(group: @group, user: current_user)).request_to_join? %>
  <%= link_to 'Invite Members', invite_group_memberships_path(@group), class: 'button secondary' if policy(Membership.new(group: @group, user: current_user)).invite? %>
  <%= link_to 'Begin Locking Process for Group', finalize_draw_group_path(@draw, @group), method: :put, data: { confirm: 'This will begin the process of confirming this housing group and cannot be undone. Are you sure you want to proceed?' }, class: 'button' if policy(@group).finalize? %>
  <%= link_to 'Lock Group', lock_draw_group_path(@draw, @group), method: :put, class: 'button alert' if policy(@group).lock? %>
  <%= link_to 'Unlock All Members', unlock_draw_group_path(@draw, @group), method: :put, class: 'button alert' if policy(@group).unlock? %>
  <% if @group.suite.present? && policy(SuiteAssignment.new(groups: [@group], draw: @group.draw)).new? %>
    <%= simple_form_for @group, url: group_suite_assignment_path(@group), method: :delete, html: { class: 'hidden-form' } do |f| %>
      <%= f.input :suite, as: :hidden, input_html: { value: '' } %>
      <%= f.submit 'Remove suite' %>
    <% end %>
  <% end %>
  <% if policy(@group).assign_rooms? %>
    <%= link_to 'Assign rooms', new_group_room_assignment_path(@group), class: 'button' %>
  <% end %>
  <% if policy(@group).edit_room_assignment? %>
    <%= link_to 'Edit room assignments', edit_group_room_assignment_path(@group), class: 'button' %>
  <% end %>
  <% if policy(@group).make_drawless? %>
    <%= link_to 'Make special group', make_drawless_draw_group_path(@draw, @group), method: :patch, data: { confirm: 'Are you sure you want to remove this group and its members from the draw?' },
      **with_tooltip(text: 'Remove this group and its members from the draw and convert it to a special group.', class_override: 'button alert') %>
  <% end %>
  <%= link_to('Disband', draw_group_path(@draw, @group), method: :delete, data: { confirm: 'Are you sure you want to disband this group?' }, class: 'button alert') if policy(@group).destroy? %>
</div>
<%= link_to 'Return to draw', draw_path(@draw) %>

<% content_for :sidebar do %>
  <h1 class="h3">Compatible Suites</h1>
  <h2 class="h4"><%= @same_size_groups_count %> <%= 'group'.pluralize(@same_size_groups_count) %> of size <%= @group.size %></h2>
  <h2 class="h4"><%= @compatible_suites_count %> available <%= size_str(@group.size).capitalize.pluralize(@compatible_suites_count) %></h2>
  <% unless @compatible_suites_count.zero? %>
    <%= render 'groups/suites_table', suites: @compatible_suites.group_by(&:building) %>
  <% end %>
<% end %>