config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(index new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
  end

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resource :students, only: %i(edit update), controller: :draw_students do
      collection do
        patch 'bulk_assign'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/college.rb
# frozen_string_literal: true

# Model for site configuration / individual colleges. Will be used for
# multi-tenancy in the future.
#
# @attr name [String] the college name
# @attr admin_email [String] the admin e-mail for the college
# @attr dean [String] the name of the college dean / head
# @attr site_url [String] the full url (including http/https) for the Vesta site
#   for the college
# @attr floor_plan_url [String] the url to access floor plans
# @attr student_info_text [Text] a paragraph of text viewable on the student
#   dashboard
class College < ApplicationRecord
  validates :name, presence: true
  validates :admin_email, presence: true
  validates :dean, presence: true
  validates :subdomain, uniqueness: { case_sensitive: false }

  before_validation :set_subdomain
  before_update :freeze_subdomain
  after_create :create_schema!
  after_destroy :drop_schema!

  has_many :users

  self.table_name = 'shared.colleges'

  # Returns the current Apartment tenant. Raises an ActiveRecord::RecordNotFound
  # exception if the tenant does not exist (shouldn't be possible unless we're
  # in the public schema).
  #
  # @return [College] the current college or a null college
  def self.current
    find_by!(subdomain: Apartment::Tenant.current)
  end

  # Activate a given college, by subdomain
  #
  # @param subdomain [String] the subdomain of the college to activate
  def self.activate!(subdomain)
    find_by(subdomain: subdomain).activate!
  end

  # Switch to the college's Postgres schema
  def activate!
    Apartment::Tenant.switch!(subdomain)
  end

  # Return the college host - prepends the subdomain to the ENV-configured
  # canonical host.
  #
  # @return [String] the host for a given college's subdomain
  def host
    "#{subdomain}.#{env('APPLICATION_HOST')}"
  end

  private

  def set_subdomain
    return if subdomain.present?
    assign_attributes(subdomain: URI.encode_www_form_component(name&.downcase))
  end

  def freeze_subdomain
    return unless will_save_change_to_subdomain?
    throw(:abort)
  end

  def create_schema!
    Apartment::Tenant.create(subdomain)
  end

  def drop_schema!
    Apartment::Tenant.drop(subdomain)
  end
end

app/controllers/admin/colleges_controller.rb
# frozen_string_literal: true

module Admin
  class CollegesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = College.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   College.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/colleges_controller.rb
# frozen_string_literal: true

#
# Controller for College resources
class CollegesController < ApplicationController
  prepend_before_action :set_college, except: %i(index new create)
  skip_before_action :set_current_college, only: %i(index)

  def index
    @colleges = College.all.order(name: :asc)
  end

  def show; end

  def new
    @college = College.new
  end

  def create
    result = CollegeCreator.create!(params: college_params,
                                    user_for_access: current_user)
    @college = result[:college]
    handle_action(action: 'new', **result)
  end

  def edit; end

  def update
    result = Updater.new(object: @college, name_method: :name,
                         params: college_params).update
    @college = result[:record]
    handle_action(action: 'edit', **result)
  end

  private

  def authorize!
    if @college
      authorize @college
    else
      authorize College
    end
  end

  def unauthenticated?
    action_name == 'index' && Apartment::Tenant.current == 'public'
  end

  def college_params
    params.require(:college).permit(:name, :admin_email, :dean, :floor_plan_url,
                                    :student_info_text, :subdomain)
  end

  def set_college
    @college = College.find(params[:id])
  end
end

app/views/colleges/_form.html.erb
<%= simple_form_for @college do |f| %>
  <%= f.input :name %>
  <% unless @college.persisted? %>
    <%= f.input :subdomain, hint: 'The URL the college site will be accessible at, e.g. housing-sm for housing-sm.yalecollege.yale.edu' %>
  <% end %>
  <%= f.input :admin_email, label: 'Administrator e-mail', hint: 'Used in e-mails sent to students' %>
  <%= f.input :dean, hint: 'Used in e-mail signatures' %>
  <%= f.input :floor_plan_url, label: 'Floor plan URL', hint: 'The web address used to view the floor plans' %>
  <%= f.input :student_info_text, label: 'Student welcome text', hint: 'This text is displayed to all students; you should outline your policies and any other information they may need to participate in the housing draw.' %>
  <%= f.submit %>
<% end %>

app/views/colleges/edit.html.erb
<% provide(:title, 'Edit Settings') %>
<h1>Edit Settings</h1>
<%= render "form", college: @college %>
<%= link_to 'Cancel', college_path(@college) %>

app/views/colleges/index.html.erb
<div class="homepage-hero">
  <h1>Welcome to Vesta</h1>
  <p>
  Vesta is a web app that manages the housing process for Yale's residential colleges. To proceed please click on the link for your college below:
  </p>
  <ul>
    <% @colleges.each do |college| %>
      <li><%= link_to college.name, root_url(host: college.host) %></li>
    <% end %>
  </ul>
</div>

app/views/colleges/new.html.erb
<% provide(:title, 'Create College') %>
<h1>Create College</h1>
<%= render "form", college: @college %>

app/views/colleges/show.html.erb
<% provide(:title, 'Settings') %>
<h1 class="college-name"><%= @college.name %></h1>
<dl>
  <dt>Dean</dt>
  <dd><%= @college.dean %></dd>
  <dt>Admin E-mail</dt>
  <dd><%= @college.admin_email %></dd>
  <dt>Site URL</dt>
  <dd><%= root_url(host: @college.host) %></dd>
</dl>
<div>
  <% if policy(@college).edit? %>
    <%= link_to 'Edit settings', edit_college_path(@college), class: 'button secondary' %>
  <% end %>
</div>